In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
#import data source
df=pd.read_csv("E:\code\Project\Score_Prediction\data\stud.csv")
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.shape

(1000, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [10]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [11]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [14]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.nunique()  #check unique values in each columns

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [ ]:
df['race_ethnic ity'].unique() #check what are unique values

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [ ]:
numerical_feature=[feature for feature in df.columns if df[feature].dtype!='O']
numerical_feature

['math_score', 'reading_score', 'writing_score']

In [40]:
categorcal_feature=[feature for feature in df.columns if df[feature].dtype=='O']
categorcal_feature

['gender',
 'race_ethnicity',
 'parental_level_of_education',
 'lunch',
 'test_preparation_course']

In [42]:
df[numerical_feature].head()

   math_score  reading_score  writing_score
0          72             72             74
1          69             90             88
2          90             95             93
3          47             57             44
4          76             78             75

# Task is to predict total score and average score

In [45]:
df['Total score']=df['math_score']+df['reading_score']+df['writing_score']
df['average score']=df['Total score']/3
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,Total score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [44]:
df['average score']

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Name: average score, Length: 1000, dtype: float64

In [46]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import  warnings

In [47]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,Total score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [59]:
new_df=df.drop(['math_score','reading_score','writing_score','average score'],axis=1)

In [60]:
X=new_df.drop(['Total score'],axis=1)
Y=new_df['Total score']

In [61]:
X.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course
0,female,group B,bachelor's degree,standard,none
1,female,group C,some college,standard,completed
2,female,group B,master's degree,standard,none
3,male,group A,associate's degree,free/reduced,none
4,male,group C,some college,standard,none

In [65]:
num_feat=X.select_dtypes(exclude="object").columns
cat_feat=X.select_dtypes(include="object").columns
print(num_feat,"----",cat_feat)

Index([], dtype='object') ---- Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object')

In [102]:
#all are cat variable in independent variable 
from sklearn.preprocessing import OneHotEncoder

In [103]:
cat_encoder=OneHotEncoder(sparse_output=False)

In [125]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.30,random_state=42)

In [126]:
X_train=cat_encoder.fit_transform(x_train)
X_test=cat_encoder.transform(x_test)

In [127]:
def evaluate_model(true,predict):
    mae=mean_absolute_error(true,predict)
    mse=mean_squared_error(true,predict)
    score=r2_score(true,predict)
    return mae,mse,score

In [133]:
models={
    "Linear Regression": LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "decision tree":DecisionTreeRegressor(),
    "XGB Regre":XGBRegressor(),
    "catboost":CatBoostRegressor(),
    "adaboost":AdaBoostRegressor()
}

model_list=[]
score=[]
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)  

    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    train_mae,train_mse,train_score=evaluate_model(y_train,y_train_pred)
    test_mae,test_mse,test_score=evaluate_model(y_test,y_test_pred)
    

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    print("training accuracy")
    print("train_mae",train_mae)
    print("train_mse",train_mse)
    print("train_score",train_score)
    print("   ")
    print("test accuracy")
    print("test_mae",test_mae)
    print("test_mse",test_mse)
    print("test_score",test_score)
    print("--------------------")

Linear Regression
training accuracy
train_mae 29.47564660679257
train_mse 1318.4371687836249
train_score 0.2380867653463341

test accuracy
test_mae 31.710736024883094
test_mse 1585.4100039158336
test_score 0.2185897235770785
--------------------
Lasso
training accuracy
train_mae 29.81498063038781
train_mse 1369.509032751793
train_score 0.20857278470539165

test accuracy
test_mae 32.43730216186284
test_mse 1680.4036855218715
test_score 0.17176963361999142
--------------------
Ridge
training accuracy
train_mae 29.47486150777204
train_mse 1318.4480719494354
train_score 0.23808046450278442

test accuracy
test_mae 31.71500743357447
test_mse 1586.0595991476378
test_score 0.21826955378605073
--------------------
decision tree
training accuracy
train_mae 24.257534330748616
train_mse 976.776507389436
train_score 0.435529454190522

test accuracy
test_mae 37.40510617160617
test_mse 2155.1508617881113
test_score -0.062221776375487536
--------------------
XGB Regre
training accuracy
train_mae 24.27767562866211
train_mse 976.8115234375
train_score 0.43550926446914673

test accuracy
test_mae 37.51227951049805
test_mse 2177.742919921875
test_score -0.07335686683654785
--------------------
Learning rate set to 0.038699
0:	learn: 41.2719165	total: 957us	remaining: 957ms
1:	learn: 40.9570333	total: 1.83ms	remaining: 915ms
2:	learn: 40.6815041	total: 2.65ms	remaining: 880ms
3:	learn: 40.4093423	total: 3.35ms	remaining: 834ms
4:	learn: 40.1585473	total: 4.06ms	remaining: 808ms
5:	learn: 39.9549219	total: 4.7ms	remaining: 779ms
6:	learn: 39.7423390	total: 5.38ms	remaining: 763ms
7:	learn: 39.5119386	total: 6.09ms	remaining: 755ms
8:	learn: 39.3154447	total: 6.81ms	remaining: 750ms
9:	learn: 39.0980807	total: 7.49ms	remaining: 741ms
10:	learn: 38.9311888	total: 8.21ms	remaining: 738ms
11:	learn: 38.7815633	total: 8.77ms	remaining: 722ms
12:	learn: 38.6055009	total: 9.54ms	remaining: 725ms
13:	learn: 38.4376706	total: 10.3ms	remaining: 724ms
14:	learn: 38.3117329	total: 11ms	remaining: 725ms
15:	learn: 38.1454871	total: 11.8ms	remaining: 729ms
16:	learn: 38.0346530	total: 12.6ms	remaining: 729ms
17:	learn: 37.8834119	total: 13.4ms	remaining: 730ms
18:	learn: 37.7546658	total: 14.2ms	remaining: 731ms
19:	learn: 37.6259362	total: 15.1ms	remaining: 739ms
20:	learn: 37.5106311	total: 15.9ms	remaining: 742ms
21:	learn: 37.4762324	total: 16.3ms	remaining: 726ms
22:	learn: 37.3447725	total: 17.1ms	remaining: 725ms
23:	learn: 37.2274610	total: 17.8ms	remaining: 724ms
24:	learn: 37.1224795	total: 18.5ms	remaining: 723ms
25:	learn: 37.0064176	total: 19.2ms	remaining: 720ms
26:	learn: 36.8906771	total: 19.9ms	remaining: 718ms
27:	learn: 36.7934320	total: 20.6ms	remaining: 714ms
28:	learn: 36.7070573	total: 21.2ms	remaining: 709ms
29:	learn: 36.6156674	total: 21.9ms	remaining: 707ms
30:	learn: 36.5252133	total: 22.6ms	remaining: 707ms
31:	learn: 36.4370616	total: 23.3ms	remaining: 704ms
32:	learn: 36.3642471	total: 24.1ms	remaining: 705ms
33:	learn: 36.2819570	total: 24.9ms	remaining: 706ms
34:	learn: 36.2158394	total: 25.6ms	remaining: 705ms
35:	learn: 36.1601133	total: 26.4ms	remaining: 706ms
36:	learn: 36.0909819	total: 27.2ms	remaining: 707ms
37:	learn: 36.0479616	total: 28ms	remaining: 708ms
38:	learn: 36.0239748	total: 28.3ms	remaining: 698ms
39:	learn: 35.9556687	total: 29ms	remaining: 697ms
40:	learn: 35.9117976	total: 29.8ms	remaining: 698ms
41:	learn: 35.8490865	total: 30.7ms	remaining: 699ms
42:	learn: 35.8400943	total: 31.1ms	remaining: 691ms
43:	learn: 35.7962521	total: 31.8ms	remaining: 690ms
44:	learn: 35.7346540	total: 32.6ms	remaining: 691ms
45:	learn: 35.7191986	total: 33ms	remaining: 685ms
46:	learn: 35.6821090	total: 33.7ms	remaining: 684ms
47:	learn: 35.6346602	total: 34.4ms	remaining: 683ms
48:	learn: 35.5738243	total: 35.3ms	remaining: 685ms
49:	learn: 35.5415587	total: 36ms	remaining: 685ms
50:	learn: 35.5004797	total: 36.7ms	remaining: 683ms
51:	learn: 35.4616785	total: 37.5ms	remaining: 683ms
52:	learn: 35.4063677	total: 38.3ms	remaining: 684ms
53:	learn: 35.3588785	total: 39ms	remaining: 684ms
54:	learn: 35.3291016	total: 39.7ms	remaining: 683ms
55:	learn: 35.2802249	total: 40.2ms	remaining: 678ms
56:	learn: 35.2368917	total: 40.8ms	remaining: 675ms
57:	learn: 35.2001701	total: 41.3ms	remaining: 671ms
58:	learn: 35.1584867	total: 42ms	remaining: 669ms
59:	learn: 35.1235501	total: 42.6ms	remaining: 667ms
60:	learn: 35.0842046	total: 43.1ms	remaining: 663ms
61:	learn: 35.0506535	total: 43.6ms	remaining: 659ms
62:	learn: 35.0097468	total: 44.1ms	remaining: 655ms
63:	learn: 34.9727186	total: 44.5ms	remaining: 650ms
64:	learn: 34.9650443	total: 44.8ms	remaining: 645ms
65:	learn: 34.9253737	total: 45.3ms	remaining: 642ms
66:	learn: 34.8917988	total: 45.9ms	remaining: 639ms
67:	learn: 34.8553460	total: 46.4ms	remaining: 636ms
68:	learn: 34.8195473	total: 47ms	remaining: 635ms
69:	learn: 34.7792808	total: 47.6ms	remaining: 633ms
70:	learn: 34.7486440	total: 48.2ms	remaining: 630ms
71:	learn: 34.7358254	total: 48.6ms	remaining: 627ms
72:	learn: 34.7031263	total: 49.2ms	remaining: 625ms
73:	learn: 34.6843903	total: 49.9ms	remaining: 624ms
74:	learn: 34.6804865	total: 50.3ms	remaining: 620ms
75:	learn: 34.6617631	total: 50.8ms	remaining: 618ms
76:	learn: 34.6455729	total: 51.4ms	remaining: 616ms
77:	learn: 34.6124737	total: 51.9ms	remaining: 614ms
78:	learn: 34.5861773	total: 52.6ms	remaining: 614ms
79:	learn: 34.5726999	total: 53.2ms	remaining: 612ms
80:	learn: 34.5677095	total: 53.7ms	remaining: 609ms
81:	learn: 34.5622633	total: 54.3ms	remaining: 607ms
82:	learn: 34.5572035	total: 54.7ms	remaining: 605ms
83:	learn: 34.5314693	total: 55.5ms	remaining: 606ms
84:	learn: 34.5239454	total: 56.2ms	remaining: 605ms
85:	learn: 34.4994795	total: 56.9ms	remaining: 604ms
86:	learn: 34.4919459	total: 57.3ms	remaining: 602ms
87:	learn: 34.4705805	total: 57.9ms	remaining: 600ms
88:	learn: 34.4681564	total: 58.1ms	remaining: 595ms
89:	learn: 34.4504752	total: 58.7ms	remaining: 594ms
90:	learn: 34.4224498	total: 59.3ms	remaining: 592ms
91:	learn: 34.4033785	total: 60ms	remaining: 592ms
92:	learn: 34.3952690	total: 60.5ms	remaining: 590ms
93:	learn: 34.3793130	total: 61.1ms	remaining: 589ms
94:	learn: 34.3584731	total: 61.6ms	remaining: 587ms
95:	learn: 34.3375117	total: 62.1ms	remaining: 584ms
96:	learn: 34.3162213	total: 62.5ms	remaining: 582ms
97:	learn: 34.3128606	total: 62.8ms	remaining: 578ms
98:	learn: 34.3028643	total: 63.3ms	remaining: 576ms
99:	learn: 34.2993632	total: 63.7ms	remaining: 573ms
100:	learn: 34.2717545	total: 64.4ms	remaining: 573ms
101:	learn: 34.2498252	total: 64.8ms	remaining: 571ms
102:	learn: 34.2353971	total: 65.4ms	remaining: 569ms
103:	learn: 34.2148305	total: 65.8ms	remaining: 567ms
104:	learn: 34.1948518	total: 66.5ms	remaining: 567ms
105:	learn: 34.1824205	total: 67ms	remaining: 565ms
106:	learn: 34.1579842	total: 67.5ms	remaining: 564ms
107:	learn: 34.1487288	total: 68ms	remaining: 562ms
108:	learn: 34.1268334	total: 68.6ms	remaining: 561ms
109:	learn: 34.1068164	total: 69.2ms	remaining: 560ms
110:	learn: 34.0927004	total: 69.7ms	remaining: 559ms
111:	learn: 34.0728786	total: 70.2ms	remaining: 557ms
112:	learn: 34.0660287	total: 70.8ms	remaining: 555ms
113:	learn: 34.0573010	total: 71.3ms	remaining: 554ms
114:	learn: 34.0411377	total: 71.8ms	remaining: 552ms
115:	learn: 34.0247694	total: 72.3ms	remaining: 551ms
116:	learn: 34.0089663	total: 72.8ms	remaining: 549ms
117:	learn: 34.0061895	total: 73.1ms	remaining: 547ms
118:	learn: 33.9910919	total: 73.6ms	remaining: 545ms
119:	learn: 33.9890699	total: 73.8ms	remaining: 541ms
120:	learn: 33.9731870	total: 74.3ms	remaining: 539ms
121:	learn: 33.9691756	total: 74.6ms	remaining: 537ms
122:	learn: 33.9684173	total: 74.8ms	remaining: 534ms
123:	learn: 33.9465644	total: 75.3ms	remaining: 532ms
124:	learn: 33.9458751	total: 75.6ms	remaining: 529ms
125:	learn: 33.9323765	total: 76.1ms	remaining: 528ms
126:	learn: 33.9091651	total: 76.6ms	remaining: 526ms
127:	learn: 33.8978631	total: 77ms	remaining: 525ms
128:	learn: 33.8840029	total: 77.6ms	remaining: 524ms
129:	learn: 33.8704421	total: 78ms	remaining: 522ms
130:	learn: 33.8689354	total: 78.4ms	remaining: 520ms
131:	learn: 33.8486402	total: 78.8ms	remaining: 518ms
132:	learn: 33.8283704	total: 79.2ms	remaining: 517ms
133:	learn: 33.8110560	total: 79.7ms	remaining: 515ms
134:	learn: 33.7935531	total: 80.3ms	remaining: 514ms
135:	learn: 33.7874028	total: 80.8ms	remaining: 513ms
136:	learn: 33.7703786	total: 81.3ms	remaining: 512ms
137:	learn: 33.7467532	total: 81.8ms	remaining: 511ms
138:	learn: 33.7335391	total: 82.6ms	remaining: 512ms
139:	learn: 33.7179755	total: 83.2ms	remaining: 511ms
140:	learn: 33.7050300	total: 83.8ms	remaining: 511ms
141:	learn: 33.6863817	total: 84.3ms	remaining: 509ms
142:	learn: 33.6682139	total: 84.8ms	remaining: 508ms
143:	learn: 33.6681686	total: 85.1ms	remaining: 506ms
144:	learn: 33.6623162	total: 85.5ms	remaining: 504ms
145:	learn: 33.6534553	total: 85.9ms	remaining: 503ms
146:	learn: 33.6325388	total: 86.4ms	remaining: 502ms
147:	learn: 33.6178630	total: 86.9ms	remaining: 500ms
148:	learn: 33.6065893	total: 87.3ms	remaining: 499ms
149:	learn: 33.5924890	total: 87.7ms	remaining: 497ms
150:	learn: 33.5906720	total: 88ms	remaining: 495ms
151:	learn: 33.5819089	total: 88.6ms	remaining: 494ms
152:	learn: 33.5677362	total: 89ms	remaining: 493ms
153:	learn: 33.5567555	total: 89.5ms	remaining: 492ms
154:	learn: 33.5396551	total: 90ms	remaining: 490ms
155:	learn: 33.5331050	total: 90.4ms	remaining: 489ms
156:	learn: 33.5220995	total: 90.9ms	remaining: 488ms
157:	learn: 33.5157410	total: 91.4ms	remaining: 487ms
158:	learn: 33.5029937	total: 91.8ms	remaining: 486ms
159:	learn: 33.4917448	total: 92.3ms	remaining: 484ms
160:	learn: 33.4817965	total: 92.7ms	remaining: 483ms
161:	learn: 33.4653141	total: 93.2ms	remaining: 482ms
162:	learn: 33.4615807	total: 93.8ms	remaining: 481ms
163:	learn: 33.4499774	total: 94.3ms	remaining: 481ms
164:	learn: 33.4342613	total: 94.7ms	remaining: 479ms
165:	learn: 33.4342009	total: 95ms	remaining: 477ms
166:	learn: 33.4228804	total: 95.4ms	remaining: 476ms
167:	learn: 33.4215872	total: 95.7ms	remaining: 474ms
168:	learn: 33.4085467	total: 96.2ms	remaining: 473ms
169:	learn: 33.4082229	total: 96.4ms	remaining: 471ms
170:	learn: 33.3926042	total: 96.9ms	remaining: 470ms
171:	learn: 33.3756302	total: 97.4ms	remaining: 469ms
172:	learn: 33.3585825	total: 97.8ms	remaining: 468ms
173:	learn: 33.3450415	total: 98.4ms	remaining: 467ms
174:	learn: 33.3421559	total: 98.7ms	remaining: 465ms
175:	learn: 33.3420913	total: 98.9ms	remaining: 463ms
176:	learn: 33.3323958	total: 99.3ms	remaining: 462ms
177:	learn: 33.3241483	total: 99.9ms	remaining: 461ms
178:	learn: 33.3223109	total: 100ms	remaining: 460ms
179:	learn: 33.3102052	total: 101ms	remaining: 458ms
180:	learn: 33.2918592	total: 101ms	remaining: 457ms
181:	learn: 33.2793807	total: 102ms	remaining: 456ms
182:	learn: 33.2653655	total: 102ms	remaining: 456ms
183:	learn: 33.2541340	total: 103ms	remaining: 455ms
184:	learn: 33.2448747	total: 103ms	remaining: 454ms
185:	learn: 33.2345912	total: 103ms	remaining: 453ms
186:	learn: 33.2221780	total: 104ms	remaining: 452ms
187:	learn: 33.2210147	total: 104ms	remaining: 450ms
188:	learn: 33.2103736	total: 105ms	remaining: 449ms
189:	learn: 33.2023731	total: 105ms	remaining: 448ms
190:	learn: 33.1900395	total: 106ms	remaining: 447ms
191:	learn: 33.1831342	total: 106ms	remaining: 447ms
192:	learn: 33.1625473	total: 107ms	remaining: 446ms
193:	learn: 33.1533774	total: 107ms	remaining: 445ms
194:	learn: 33.1343715	total: 108ms	remaining: 444ms
195:	learn: 33.1227751	total: 108ms	remaining: 443ms
196:	learn: 33.1056709	total: 109ms	remaining: 442ms
197:	learn: 33.0917875	total: 109ms	remaining: 442ms
198:	learn: 33.0807265	total: 109ms	remaining: 440ms
199:	learn: 33.0713830	total: 110ms	remaining: 439ms
200:	learn: 33.0540892	total: 110ms	remaining: 438ms
201:	learn: 33.0427162	total: 111ms	remaining: 438ms
202:	learn: 33.0294019	total: 111ms	remaining: 437ms
203:	learn: 33.0224845	total: 112ms	remaining: 436ms
204:	learn: 33.0077271	total: 112ms	remaining: 436ms
205:	learn: 33.0009090	total: 113ms	remaining: 435ms
206:	learn: 32.9868265	total: 113ms	remaining: 434ms
207:	learn: 32.9740964	total: 114ms	remaining: 433ms
208:	learn: 32.9654084	total: 114ms	remaining: 432ms
209:	learn: 32.9553020	total: 115ms	remaining: 431ms
210:	learn: 32.9461154	total: 115ms	remaining: 431ms
211:	learn: 32.9326389	total: 116ms	remaining: 430ms
212:	learn: 32.9171231	total: 116ms	remaining: 429ms
213:	learn: 32.9122446	total: 117ms	remaining: 428ms
214:	learn: 32.9043872	total: 117ms	remaining: 428ms
215:	learn: 32.8970072	total: 118ms	remaining: 427ms
216:	learn: 32.8852284	total: 118ms	remaining: 426ms
217:	learn: 32.8766148	total: 118ms	remaining: 425ms
218:	learn: 32.8688940	total: 119ms	remaining: 424ms
219:	learn: 32.8574785	total: 119ms	remaining: 423ms
220:	learn: 32.8493092	total: 120ms	remaining: 422ms
221:	learn: 32.8404045	total: 120ms	remaining: 421ms
222:	learn: 32.8285968	total: 121ms	remaining: 421ms
223:	learn: 32.8201488	total: 121ms	remaining: 420ms
224:	learn: 32.8123402	total: 122ms	remaining: 419ms
225:	learn: 32.8063222	total: 122ms	remaining: 418ms
226:	learn: 32.7992239	total: 122ms	remaining: 417ms
227:	learn: 32.7888942	total: 123ms	remaining: 416ms
228:	learn: 32.7775259	total: 123ms	remaining: 415ms
229:	learn: 32.7694335	total: 124ms	remaining: 414ms
230:	learn: 32.7612345	total: 124ms	remaining: 413ms
231:	learn: 32.7475530	total: 125ms	remaining: 412ms
232:	learn: 32.7382071	total: 125ms	remaining: 412ms
233:	learn: 32.7330060	total: 125ms	remaining: 411ms
234:	learn: 32.7192069	total: 126ms	remaining: 410ms
235:	learn: 32.7090279	total: 126ms	remaining: 409ms
236:	learn: 32.7018574	total: 127ms	remaining: 409ms
237:	learn: 32.6921903	total: 127ms	remaining: 408ms
238:	learn: 32.6869999	total: 128ms	remaining: 407ms
239:	learn: 32.6821450	total: 128ms	remaining: 406ms
240:	learn: 32.6752638	total: 129ms	remaining: 406ms
241:	learn: 32.6634402	total: 129ms	remaining: 405ms
242:	learn: 32.6544962	total: 130ms	remaining: 404ms
243:	learn: 32.6492356	total: 130ms	remaining: 403ms
244:	learn: 32.6432535	total: 131ms	remaining: 403ms
245:	learn: 32.6384308	total: 131ms	remaining: 402ms
246:	learn: 32.6281534	total: 132ms	remaining: 401ms
247:	learn: 32.6189596	total: 132ms	remaining: 400ms
248:	learn: 32.6037057	total: 132ms	remaining: 400ms
249:	learn: 32.5993469	total: 133ms	remaining: 399ms
250:	learn: 32.5929968	total: 133ms	remaining: 398ms
251:	learn: 32.5822061	total: 134ms	remaining: 397ms
252:	learn: 32.5739317	total: 134ms	remaining: 397ms
253:	learn: 32.5702604	total: 135ms	remaining: 396ms
254:	learn: 32.5648263	total: 135ms	remaining: 395ms
255:	learn: 32.5607134	total: 136ms	remaining: 394ms
256:	learn: 32.5546217	total: 136ms	remaining: 394ms
257:	learn: 32.5506782	total: 137ms	remaining: 393ms
258:	learn: 32.5459352	total: 137ms	remaining: 392ms
259:	learn: 32.5364218	total: 138ms	remaining: 392ms
260:	learn: 32.5295368	total: 138ms	remaining: 391ms
261:	learn: 32.5267390	total: 139ms	remaining: 390ms
262:	learn: 32.5177707	total: 139ms	remaining: 390ms
263:	learn: 32.5136813	total: 140ms	remaining: 389ms
264:	learn: 32.5094060	total: 140ms	remaining: 388ms
265:	learn: 32.5007420	total: 140ms	remaining: 388ms
266:	learn: 32.4924852	total: 141ms	remaining: 387ms
267:	learn: 32.4858282	total: 142ms	remaining: 387ms
268:	learn: 32.4759173	total: 142ms	remaining: 386ms
269:	learn: 32.4661690	total: 143ms	remaining: 385ms
270:	learn: 32.4601487	total: 143ms	remaining: 385ms
271:	learn: 32.4508031	total: 144ms	remaining: 384ms
272:	learn: 32.4468930	total: 144ms	remaining: 383ms
273:	learn: 32.4391800	total: 144ms	remaining: 383ms
274:	learn: 32.4335277	total: 145ms	remaining: 382ms
275:	learn: 32.4299074	total: 145ms	remaining: 381ms
276:	learn: 32.4266619	total: 146ms	remaining: 380ms
277:	learn: 32.4194356	total: 146ms	remaining: 380ms
278:	learn: 32.4084176	total: 147ms	remaining: 379ms
279:	learn: 32.4038134	total: 147ms	remaining: 378ms
280:	learn: 32.4002603	total: 148ms	remaining: 378ms
281:	learn: 32.3940516	total: 148ms	remaining: 377ms
282:	learn: 32.3875172	total: 149ms	remaining: 376ms
283:	learn: 32.3847914	total: 149ms	remaining: 376ms
284:	learn: 32.3793678	total: 149ms	remaining: 375ms
285:	learn: 32.3761234	total: 150ms	remaining: 375ms
286:	learn: 32.3706798	total: 151ms	remaining: 374ms
287:	learn: 32.3656909	total: 151ms	remaining: 373ms
288:	learn: 32.3573148	total: 151ms	remaining: 373ms
289:	learn: 32.3534129	total: 152ms	remaining: 372ms
290:	learn: 32.3486296	total: 152ms	remaining: 371ms
291:	learn: 32.3422718	total: 153ms	remaining: 371ms
292:	learn: 32.3356134	total: 153ms	remaining: 370ms
293:	learn: 32.3307902	total: 154ms	remaining: 369ms
294:	learn: 32.3247127	total: 154ms	remaining: 369ms
295:	learn: 32.3157362	total: 155ms	remaining: 368ms
296:	learn: 32.3112857	total: 155ms	remaining: 367ms
297:	learn: 32.3049885	total: 156ms	remaining: 367ms
298:	learn: 32.2990452	total: 156ms	remaining: 366ms
299:	learn: 32.2920250	total: 157ms	remaining: 366ms
300:	learn: 32.2888302	total: 157ms	remaining: 365ms
301:	learn: 32.2827096	total: 158ms	remaining: 365ms
302:	learn: 32.2773275	total: 158ms	remaining: 364ms
303:	learn: 32.2715236	total: 159ms	remaining: 364ms
304:	learn: 32.2686789	total: 159ms	remaining: 363ms
305:	learn: 32.2643966	total: 160ms	remaining: 362ms
306:	learn: 32.2609302	total: 160ms	remaining: 362ms
307:	learn: 32.2582821	total: 161ms	remaining: 361ms
308:	learn: 32.2518881	total: 161ms	remaining: 360ms
309:	learn: 32.2486320	total: 162ms	remaining: 360ms
310:	learn: 32.2467370	total: 162ms	remaining: 359ms
311:	learn: 32.2439146	total: 162ms	remaining: 358ms
312:	learn: 32.2403049	total: 163ms	remaining: 358ms
313:	learn: 32.2346723	total: 163ms	remaining: 357ms
314:	learn: 32.2297613	total: 164ms	remaining: 356ms
315:	learn: 32.2238624	total: 164ms	remaining: 356ms
316:	learn: 32.2213149	total: 165ms	remaining: 355ms
317:	learn: 32.2179987	total: 165ms	remaining: 355ms
318:	learn: 32.2107338	total: 166ms	remaining: 354ms
319:	learn: 32.2028316	total: 166ms	remaining: 354ms
320:	learn: 32.1948372	total: 167ms	remaining: 353ms
321:	learn: 32.1912371	total: 167ms	remaining: 352ms
322:	learn: 32.1874132	total: 168ms	remaining: 352ms
323:	learn: 32.1833824	total: 168ms	remaining: 351ms
324:	learn: 32.1780180	total: 169ms	remaining: 350ms
325:	learn: 32.1730262	total: 169ms	remaining: 350ms
326:	learn: 32.1689782	total: 170ms	remaining: 349ms
327:	learn: 32.1641656	total: 170ms	remaining: 348ms
328:	learn: 32.1598033	total: 171ms	remaining: 348ms
329:	learn: 32.1534723	total: 171ms	remaining: 348ms
330:	learn: 32.1497413	total: 172ms	remaining: 347ms
331:	learn: 32.1457880	total: 172ms	remaining: 347ms
332:	learn: 32.1372599	total: 173ms	remaining: 346ms
333:	learn: 32.1319135	total: 173ms	remaining: 345ms
334:	learn: 32.1282408	total: 174ms	remaining: 345ms
335:	learn: 32.1198016	total: 174ms	remaining: 344ms
336:	learn: 32.1145434	total: 175ms	remaining: 343ms
337:	learn: 32.1107565	total: 175ms	remaining: 343ms
338:	learn: 32.1063254	total: 175ms	remaining: 342ms
339:	learn: 32.1037293	total: 176ms	remaining: 342ms
340:	learn: 32.0969094	total: 176ms	remaining: 341ms
341:	learn: 32.0903036	total: 177ms	remaining: 340ms
342:	learn: 32.0879844	total: 178ms	remaining: 340ms
343:	learn: 32.0829234	total: 178ms	remaining: 340ms
344:	learn: 32.0788293	total: 179ms	remaining: 339ms
345:	learn: 32.0728726	total: 179ms	remaining: 339ms
346:	learn: 32.0677472	total: 180ms	remaining: 338ms
347:	learn: 32.0639453	total: 180ms	remaining: 337ms
348:	learn: 32.0607200	total: 181ms	remaining: 337ms
349:	learn: 32.0564900	total: 181ms	remaining: 336ms
350:	learn: 32.0493510	total: 182ms	remaining: 336ms
351:	learn: 32.0454143	total: 182ms	remaining: 335ms
352:	learn: 32.0422663	total: 182ms	remaining: 334ms

In [129]:
score=r2_score(y_test,y_pred)
score

0.2185897235770785

In [120]:
mse=mean_squared_error(y_test,y_pred)
mse

1585.4100039158336

In [122]:
mae=mean_absolute_error(y_test,y_pred)
mae

31.710736024883094